import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Mete Nar Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <section className=' bg-blue-500 min-h-screen'>
          <h1>Hello</h1>
        </section>
      <main>
      </main>
    </div>
  )
}
